create table if not exists passport
(
    id                bigint generated by default as identity
        primary key,
    series_and_number varchar(255),
    by_whom_issued    varchar(255),
    issue_data        date,
    unit_code         varchar(255)
);

alter table passport
    owner to postgres;

create table  if not exists registration
(
    id              bigint generated by default as identity
        primary key,
    city            varchar(255),
    house_flat_name varchar(255),
    region          varchar(255),
    zip             integer
);

alter table registration
    owner to postgres;

create table  if not exists status
(
    id   integer generated by default as identity
        primary key,
    name varchar(255)
);

alter table status
    owner to postgres;

create table  if not exists clients
(
    id                bigint generated by default as identity
        primary key,
    bday              date,
    email             varchar(255),
    passport_id       bigint,
    registration_date date,
    telephone         varchar(255),
    username          varchar(255),
    registration_id   bigint
        constraint fkhkwx4rqq73nbdb09dqac9am4g
            references registration,
    status_id         integer
        constraint fkg5v3r2y5pjfoq5dttntousn4g
            references status
);

alter table clients
    owner to postgres;

