server:
  port: 6060
spring:
  datasource:
    url: jdbc:postgresql://localhost:4445/depositService
    password: 'postgres'
    username: 'postgres'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true