server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true          # включаем автоматическое определение сервисов
          lowerCaseServiceId: true
      routes:
        - id: client-service
          uri: lb://client-service  # lb:// означает использование Load Balancer
          predicates:
            - Path=/api/clients/**
        - id: deposit-service
          uri: lb://deposit-service
          predicates:
              - Path=/api/deposits/**

management:
  endpoint:
    gateway:
      enabled: true
