services:
  postgres_client:
    container_name: client_server
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clientService
    volumes:
      - postgres_client:/var/lib/postgresql/data
    ports:
      - "4444:5432"
    restart: unless-stopped

volumes:
  postgres_client:
