CREATE SEQUENCE IF NOT EXISTS clients_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS passport_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS registration_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS status_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE clients
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bday              date,
    email             VARCHAR(255),
    registration_date date,
    telephone         VARCHAR(255),
    username          VARCHAR(255),
    registration_id   BIGINT,
    status_id         INTEGER,
    CONSTRAINT clients_pkey PRIMARY KEY (id)
);

CREATE TABLE passport
(
    by_whom_issued    VARCHAR(255),
    issue_date        date,
    unit_code         VARCHAR(255),
    series_and_number VARCHAR,
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT passport_pkey PRIMARY KEY (id)
);

CREATE TABLE registration
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city            VARCHAR(255),
    house_flat_name VARCHAR(255),
    region          VARCHAR(255),
    zip             INTEGER,
    CONSTRAINT registration_pkey PRIMARY KEY (id)
);

CREATE TABLE status
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT status_pkey PRIMARY KEY (id)
);

ALTER TABLE clients
    ADD CONSTRAINT fkg5v3r2y5pjfoq5dttntousn4g FOREIGN KEY (status_id) REFERENCES status (id) ON DELETE NO ACTION;

ALTER TABLE clients
    ADD CONSTRAINT fkhkwx4rqq73nbdb09dqac9am4g FOREIGN KEY (registration_id) REFERENCES registration (id) ON DELETE NO ACTION;