services:
  postgres:
    container_name: deposit_server
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATA: /data/postgres
      POSTGRES_DB: depositService
    volumes:
      - postgres:/data/postgres
    ports:
      - "4445:5432"
    restart: unless-stopped

volumes:
  postgres: