services:
  postgres_deposit:
    container_name: deposit_server
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: depositService
    volumes:
      - postgres_deposit:/var/lib/postgresql/data
    ports:
      - "4445:5432"
    restart: unless-stopped

volumes:
  postgres_deposit:
